
import java.awt.Color;
import java.awt.Graphics;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 401
 */
public class Window extends javax.swing.JFrame {
   

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("v1");

        jTextField4.setText("15");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel5.setText("v2");

        jTextField5.setText("50");

        jLabel6.setText("v3");

        jTextField6.setText("88");

        jLabel7.setText("v4");

        jTextField7.setText("35");

        jLabel8.setText("v5");

        jTextField8.setText("75");
        jTextField8.setMinimumSize(new java.awt.Dimension(6, 140));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton2)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        Graphics pg = jPanel4.getGraphics();
        //redraws with new data
        paint(pg);
    }
    public void paint(Graphics g){
        super.paint(g);
        int v1 = Integer.parseInt(jTextField4.getText());
        int v2 = Integer.parseInt(jTextField5.getText());
        int v3 = Integer.parseInt(jTextField6.getText());
        int v4 = Integer.parseInt(jTextField7.getText());
        int v5 = Integer.parseInt(jTextField8.getText());
        Graphics pg = jPanel4.getGraphics();
        //base lines
        pg.drawLine(10,11*jPanel4.getHeight()/14+30,jPanel4.getWidth()-10, 11*jPanel4.getHeight()/14+30);
        pg.drawLine(50,50,50, jPanel4.getHeight()-10);
        //horizontal hashes
        pg.drawLine(40,jPanel4.getHeight()/14+30,60, jPanel4.getHeight()/14+30);
        pg.drawLine(40,2*jPanel4.getHeight()/14+30,60, 2*jPanel4.getHeight()/14+30);
        pg.drawLine(40,3*jPanel4.getHeight()/14+30,60, 3*jPanel4.getHeight()/14+30);
        pg.drawLine(40,4*jPanel4.getHeight()/14+30,60, 4*jPanel4.getHeight()/14+30);
        pg.drawLine(40,5*jPanel4.getHeight()/14+30,60, 5*jPanel4.getHeight()/14+30);
        pg.drawLine(40,6*jPanel4.getHeight()/14+30,60, 6*jPanel4.getHeight()/14+30);
        pg.drawLine(40,7*jPanel4.getHeight()/14+30,60, 7*jPanel4.getHeight()/14+30);
        pg.drawLine(40,8*jPanel4.getHeight()/14+30,60, 8*jPanel4.getHeight()/14+30);
        pg.drawLine(40,9*jPanel4.getHeight()/14+30,60, 9*jPanel4.getHeight()/14+30);
        pg.drawLine(40,10* jPanel4.getHeight()/14+30,60, 10*jPanel4.getHeight()/14+30);

       //vertical hashes
        pg.drawLine(jPanel4.getWidth()/8+50,11*jPanel4.getHeight()/14+20,jPanel4.getWidth()/8+50, 11*jPanel4.getHeight()/14+40);
        pg.drawLine(2*jPanel4.getWidth()/8+50,11*jPanel4.getHeight()/14+20,2*jPanel4.getWidth()/8+50, 11*jPanel4.getHeight()/14+40);
        pg.drawLine(3*jPanel4.getWidth()/8+50,11*jPanel4.getHeight()/14+20,3*jPanel4.getWidth()/8+50, 11*jPanel4.getHeight()/14+40);
        pg.drawLine(4*jPanel4.getWidth()/8+50,11*jPanel4.getHeight()/14+20,4*jPanel4.getWidth()/8+50, 11*jPanel4.getHeight()/14+40);
        pg.drawLine(5*jPanel4.getWidth()/8+50,11*jPanel4.getHeight()/14+20,5*jPanel4.getWidth()/8+50, 11*jPanel4.getHeight()/14+40);
        
        //labels on bottom
        pg.drawString("v1",jPanel4.getWidth()/8+50,jPanel4.getHeight()-20);
        pg.drawString("v2",2*jPanel4.getWidth()/8+50,jPanel4.getHeight()-20);
        pg.drawString("v3",3*jPanel4.getWidth()/8+50,jPanel4.getHeight()-20);
        pg.drawString("v4",4*jPanel4.getWidth()/8+50,jPanel4.getHeight()-20);
        pg.drawString("v5",5*jPanel4.getWidth()/8+50,jPanel4.getHeight()-20);
        //labels on side
        pg.drawString("100",20,jPanel4.getHeight()/14+30);
        pg.drawString("90",20,2*jPanel4.getHeight()/14+30);
        pg.drawString("80",20,3*jPanel4.getHeight()/14+30);
        pg.drawString("70",20,4*jPanel4.getHeight()/14+30);
        pg.drawString("60",20,5*jPanel4.getHeight()/14+30);
        pg.drawString("50",20,6*jPanel4.getHeight()/14+30);
        pg.drawString("40",20,7*jPanel4.getHeight()/14+30);
        pg.drawString("30",20,8*jPanel4.getHeight()/14+30);
        pg.drawString("20",20,9*jPanel4.getHeight()/14+30);
        pg.drawString("10",20,10*jPanel4.getHeight()/14+30);
        //graphs that refresh. 
        
        //does not exactly match as int division is off. i should cast a double here to make it me accurate.
        pg.setColor(Color.orange);
        pg.fillRect( jPanel4.getWidth()/8+40,- (v1)*(jPanel4.getHeight()/14*11) / 100  +30+(11*jPanel4.getHeight()/14 ),20   ,v1*(jPanel4.getHeight()/14*11) / 100 );
        pg.setColor(Color.yellow);
        pg.fillRect( 2*jPanel4.getWidth()/8+40,- (v2)*(jPanel4.getHeight()/14*11) / 100  +30+(11*jPanel4.getHeight()/14 ),20   ,v2*(jPanel4.getHeight()/14*11) / 100 );
        pg.setColor(Color.red);
        pg.fillRect( 3*jPanel4.getWidth()/8+40,- (v3)*(jPanel4.getHeight()/14*11) / 100  +30+(11*jPanel4.getHeight()/14 ),20   ,v3*(jPanel4.getHeight()/14*11) / 100 );
        pg.setColor(Color.GRAY);
        pg.fillRect( 4*jPanel4.getWidth()/8+40,- (v4)*(jPanel4.getHeight()/14*11) / 100  +30+(11*jPanel4.getHeight()/14 ),20   ,v4*(jPanel4.getHeight()/14*11) / 100 );
        pg.setColor(Color.blue);
        pg.fillRect( 5*jPanel4.getWidth()/8+40,- (v5)*(jPanel4.getHeight()/14*11) / 100  +30+(11*jPanel4.getHeight()/14 ),20   ,v5*(jPanel4.getHeight()/14*11) / 100 );

        

        //pg.setColor(Color.blue);
        //pg.fillRect(v1,v2,50,jPanel4.getHeight()-v2-50);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Window().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration
}
