
import java.awt.Color;
import java.awt.Graphics;
import java.util.Vector;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 401
 */

public class MPframe extends javax.swing.JFrame {

    /**
     * Creates new form MPframe
     */
    public MPframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSlider4 = new javax.swing.JSlider();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        myOvalButton1 = new MyOvalButton();
        myRectButton1 = new MyRectButton();
        myLineButton1 = new MyLineButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jPanel7 = new javax.swing.JPanel();
        myBorder1 = new MyBorder();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myOvalButton1.setText("                 ");
        myOvalButton1.setMaximumSize(new java.awt.Dimension(133, 91));
        myOvalButton1.setMinimumSize(new java.awt.Dimension(133, 33));
        myOvalButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myOvalButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(myOvalButton1);

        myRectButton1.setText("                 ");
        myRectButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRectButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(myRectButton1);

        myLineButton1.setText("                 ");
        myLineButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myLineButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(myLineButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);

        jSlider1.setMajorTickSpacing(50);
        jSlider1.setMaximum(255);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel2.add(jSlider1);

        jSlider2.setMajorTickSpacing(50);
        jSlider2.setMaximum(255);
        jSlider2.setMinorTickSpacing(10);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jPanel2.add(jSlider2);

        jSlider3.setMajorTickSpacing(50);
        jSlider3.setMaximum(255);
        jSlider3.setMinorTickSpacing(10);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });
        jPanel2.add(jSlider3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        myBorder1.setOpaque(false);
        myBorder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                myBorder1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                myBorder1MouseReleased(evt);
            }
        });
        myBorder1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                myBorder1ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout myBorder1Layout = new javax.swing.GroupLayout(myBorder1);
        myBorder1.setLayout(myBorder1Layout);
        myBorder1Layout.setHorizontalGroup(
            myBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        myBorder1Layout.setVerticalGroup(
            myBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myLineButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myLineButton1ActionPerformed
       type = 2; // TODO add your handling code here:
    }//GEN-LAST:event_myLineButton1ActionPerformed

    private void myOvalButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myOvalButton1ActionPerformed
        type = 0;        // TODO add your handling code here:
    }//GEN-LAST:event_myOvalButton1ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(jSlider1.getValue(),jSlider2.getValue(),jSlider3.getValue()));
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(jSlider1.getValue(),jSlider2.getValue(),jSlider3.getValue()));
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
        // TODO add your handling code here:
        
        jPanel3.setBackground(new Color(jSlider1.getValue(),jSlider2.getValue(),jSlider3.getValue()));
    }//GEN-LAST:event_jSlider3StateChanged

    private void myRectButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRectButton1ActionPerformed
        type = 1;        // TODO add your handling code here:
    }//GEN-LAST:event_myRectButton1ActionPerformed

    private void myBorder1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myBorder1MousePressed
        // TODO add your handling code here:
        oldx = evt.getX();
        oldy = evt.getY();
    }//GEN-LAST:event_myBorder1MousePressed

    private void myBorder1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myBorder1MouseReleased
        // TODO add your handling code here:
               newx = evt.getX();
       newy = evt.getY();
       Pics p = new Pics();
       colora=jSlider1.getValue();
        colorb=jSlider2.getValue();
        colorc=jSlider3.getValue();
       p.pic(type,oldx,oldy,newx,newy,colora,colorb,colorc);
       v.add(p);
       Graphics g = jPanel7.getGraphics();
       Pics s = v.elementAt(v.size()-1);
       
       g.setColor(new Color(colora,colorb,colorc));
       if (s.t == 0){
           g.drawOval(s.ox, s.oy,s.nx-s.ox, s.ny-s.oy);
           g.drawOval(s.nx, s.ny,s.ox-s.nx, s.oy-s.ny);
           g.drawOval(s.nx, s.oy,s.ox-s.nx,s.ny-s.oy );
           g.drawOval(s.ox, s.ny,s.nx-s.ox, s.oy-s.ny);
       }
       if (s.t == 1){
           g.drawRect(s.ox, s.oy,s.nx-s.ox, s.ny-s.oy);
           g.drawRect(s.nx, s.ny,s.ox-s.nx, s.oy-s.ny);
           g.drawRect(s.nx, s.oy,s.ox-s.nx,s.ny-s.oy );
           g.drawRect(s.ox, s.ny,s.nx-s.ox, s.oy-s.ny);
       }
       if (s.t == 2){
           g.drawLine(s.ox, s.oy,s.nx, s.ny);
        }
    }//GEN-LAST:event_myBorder1MouseReleased

    private void myBorder1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_myBorder1ComponentResized
        // TODO add your handling code here:
        Graphics pg = jPanel7.getGraphics();
    for ( int i = 0; i < v.size(); i++){
        Pics s = v.elementAt(i);
       pg.setColor(new Color(s.ca,s.cb,s.cc));
            if (s.t == 0){
           pg.drawOval(s.ox, s.oy,s.nx-s.ox, s.ny-s.oy);
           pg.drawOval(s.nx, s.ny,s.ox-s.nx, s.oy-s.ny);
           pg.drawOval(s.nx, s.oy,s.ox-s.nx,s.ny-s.oy );
           pg.drawOval(s.ox, s.ny,s.nx-s.ox, s.oy-s.ny);
       }
       if (s.t == 1){
           pg.drawRect(s.ox, s.oy,s.nx-s.ox, s.ny-s.oy);
           pg.drawRect(s.nx, s.ny,s.ox-s.nx, s.oy-s.ny);
           pg.drawRect(s.nx, s.oy,s.ox-s.nx,s.ny-s.oy );
           pg.drawRect(s.ox, s.ny,s.nx-s.ox, s.oy-s.ny);
       }
       if (s.t == 2){
           pg.drawLine(s.ox, s.oy,s.nx, s.ny);
           //g.drawLine(newx, newy,oldx-newx, oldy-newy);
           //g.drawLine(newx, oldy,oldx-newx,newy-oldy );
           //g.drawLine(oldx, newy,newx-oldx, oldy-newy);
       
        }
    }
    }//GEN-LAST:event_myBorder1ComponentResized
    
    //FROM PROJECT 6 P 2
    int type;
Vector<Pics> v = new Vector();
    int oldx, oldy,newx,newy,colora, colorb, colorc;
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MPframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MPframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MPframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MPframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MPframe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private MyBorder myBorder1;
    private MyLineButton myLineButton1;
    private MyOvalButton myOvalButton1;
    private MyRectButton myRectButton1;
    // End of variables declaration//GEN-END:variables
}
