
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.PrintJob;
import java.awt.print.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 401
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        myRectButton2 = new MyRectButton();
        myOvalButton1 = new MyOvalButton();
        myLineButton1 = new MyLineButton();
        myRRectButton1 = new MyRRectButton();
        freeHandButton1 = new FreeHandButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSlider2 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setText("Clear");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        myRectButton2.setText("                         ");
        myRectButton2.setToolTipText("");
        myRectButton2.setFocusable(false);
        myRectButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myRectButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myRectButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRectButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(myRectButton2);

        myOvalButton1.setMnemonic(' ');
        myOvalButton1.setText("                         ");
        myOvalButton1.setFocusable(false);
        myOvalButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myOvalButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myOvalButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myOvalButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(myOvalButton1);

        myLineButton1.setText("                             ");
        myLineButton1.setFocusable(false);
        myLineButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myLineButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myLineButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myLineButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(myLineButton1);

        myRRectButton1.setText("                 ");
        myRRectButton1.setFocusable(false);
        myRRectButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myRRectButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myRRectButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRRectButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(myRRectButton1);

        freeHandButton1.setText("     ");
        freeHandButton1.setActionCommand("           ");
        freeHandButton1.setFocusable(false);
        freeHandButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        freeHandButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        freeHandButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeHandButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(freeHandButton1);

        jButton2.setText("Print");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jCheckBox1.setText("Dashed");
        jCheckBox1.setFocusable(false);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jCheckBox1);

        jSlider2.setMajorTickSpacing(1);
        jSlider2.setMaximum(10);
        jSlider2.setPaintTicks(true);
        jSlider2.setSnapToTicks(true);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jToolBar1.add(jSlider2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 200));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 200));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        jSlider1.setMajorTickSpacing(50);
        jSlider1.setMaximum(255);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        jPanel1.add(jPanel8);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentResized(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setText("Quit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
Shape shape = new Shape();



    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Graphics g = jPanel2.getGraphics();
        g.clearRect(0, 0, jPanel2.getWidth(), jPanel2.getHeight());
        bg = jPanel2.createImage(jPanel2.getWidth(), jPanel2.getHeight());
        fg = jPanel2.createImage(jPanel2.getWidth(), jPanel2.getHeight());
        
    }//GEN-LAST:event_jButton1ActionPerformed
    int oldx, oldy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        oldx = evt.getX();
        oldy = evt.getY();  
        if(bg==null){
            bg=jPanel2.createImage(jPanel2.getWidth(), jPanel2.getHeight());
            fg=jPanel2.createImage(jPanel2.getWidth(),jPanel2.getHeight());
            Graphics bgg = bg.getGraphics();
             bgg.drawImage(fg,0,0,null);
        }
        shape.x1=oldx;
        shape.y1=oldy;
       // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed
int newx, newy, colora, colorb, colorc;
    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        // TODO add your handling code here:
       newx = evt.getX();
       newy = evt.getY();

       //colora=jSlider1.getValue();
       // colorb=jSlider2.getValue();
        //colorc=jSlider3.getValue();
        Graphics g = jPanel2.getGraphics();
       
      shape.draw(g, oldx, oldy, newx, newy, colora, colorb, colorc,dash,jSlider2.getValue());
        
       Graphics bgg = bg.getGraphics();
       bgg.drawImage(fg,0,0,null);
       
       // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseReleased

    private void myRRectButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRRectButton1ActionPerformed
        shape = new RRect();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_myRRectButton1ActionPerformed

    private void myLineButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myLineButton1ActionPerformed
       shape = new Line(); // TODO add your handling code here:
    }//GEN-LAST:event_myLineButton1ActionPerformed

    private void myOvalButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myOvalButton1ActionPerformed
shape = new Oval();        // TODO add your handling code here:
    }//GEN-LAST:event_myOvalButton1ActionPerformed

    private void myRectButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRectButton2ActionPerformed
shape = new Rect();        // TODO add your handling code here:
    }//GEN-LAST:event_myRectButton2ActionPerformed

    private void jPanel2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentResized
       setBackground();
       jPanel7.setBackground(new Color(colora, colorb, colorc));
        Graphics fgg = fg.getGraphics();
        
     
        fgg.drawImage(bg,0,0,null);
        Graphics g = jPanel2.getGraphics();
         g.drawImage(fg,0,0,null);
        /*for (int i = 0; i <shapes.size(); i++){

           Shape s = (Shape) shapes.elementAt(i);
           s.draw();
           * 
           */
       //}// TODO add your handling code here:
    }//GEN-LAST:event_jPanel2ComponentResized

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Graphics g = jPanel2.getGraphics();
        g.clearRect(0, 0, jPanel2.getWidth(), jPanel2.getHeight());
        bg = jPanel2.createImage(jPanel2.getWidth(), jPanel2.getHeight());
        fg = jPanel2.createImage(jPanel2.getWidth(), jPanel2.getHeight());
        // TODO add your handling fgg.drawImage(bg,0,0,null);code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
Image bg,fg;
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        
        
        Graphics fgg = fg.getGraphics();
        newx=evt.getX();
        newy=evt.getY();
        fgg.drawImage(bg,0,0,null);
        shape.draw(fgg,oldx,oldy,newx,newy,colora,colorb,colorc,dash,jSlider2.getValue());
        Graphics g = jPanel2.getGraphics();
        g.drawImage(fg,0,0,null);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        if (evt.getX() < jPanel3.getWidth() && evt.getX() > 0 && evt.getY() < jPanel3.getHeight() && evt.getY() > 0) {
            colora = 255 * evt.getX() / jPanel3.getWidth();
            colorb = 255 * evt.getY() / jPanel3.getHeight();
            colorc = jSlider1.getValue();
            /*
             * //jPanel3.getGraphics().clearRect(evt.getX()-100,evt.getY()-100,500,500);
             * GradientPaint gp = new GradientPaint(0,0,new Color(0,0,c),
             * jPanel3.getWidth(),jPanel3.getHeight() , new Color(255,255,c));
             * Graphics2D g2d = (Graphics2D)jPanel3.getGraphics();
             * g2d.setPaint(gp); g2d.fillRect(0, 0,
             * jPanel3.getWidth(),jPanel3.getHeight());
             * //jPanel3.getGraphics().drawRect(evt.getX()-3,evt.getY()-3,3,3);
        *
             */

            //c=jSlider1.getValue();

            jPanel7.setBackground(new Color(colora, colorb, colorc));
            // TODO add your handling code here:
        }
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        setBackground();
    }//GEN-LAST:event_jSlider1StateChanged

    private void freeHandButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeHandButton1ActionPerformed
shape = new FreeHand();        // TODO add your handling code here:
    }//GEN-LAST:event_freeHandButton1ActionPerformed
int dash = 0;
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if (dash ==0)
           dash = 1;
       else
           dash = 0;// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider2StateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       PrinterJob pj = PrinterJob.getPrinterJob();
       PageFormat pf = pj.pageDialog(new PageFormat());
       if (pj.printDialog()){
           Book b = new Book();
           Printable printable = new MyPrintable(bg);
           b.append(printable, pf);
           pj.setPageable(b);
           try {
               pj.print();
           }catch(PrinterException ex){
               Logger.getLogger(Window.class.getName()).log(Level.SEVERE,null,ex);
           }
       }
    }//GEN-LAST:event_jButton2ActionPerformed
 public void setBackground(){
     Graphics g;
        g= jPanel3.getGraphics();
         colorc=jSlider1.getValue();
         for(int i = 0; i < 255;i+=3){
             for(int j = 0; j < 255;j+=3){
             g.setColor(new Color(j,i,colorc));
             g.fillRect(j*jPanel3.getWidth()/255,i*jPanel3.getHeight()/255,4*jPanel3.getWidth()/255,4*jPanel3.getHeight()/255);
             }
         }
         jPanel7.setBackground(new Color(colora, colorb, colorc));
    }                         
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Window().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FreeHandButton freeHandButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JToolBar jToolBar1;
    private MyLineButton myLineButton1;
    private MyOvalButton myOvalButton1;
    private MyRRectButton myRRectButton1;
    private MyRectButton myRectButton2;
    // End of variables declaration//GEN-END:variables
}
